// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhnmsaebbljqpcvsxpfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJobm1zYWViYmxqcXBjdnN4cGZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTMzODYsImV4cCI6MjA2Mzc2OTM4Nn0.7-WDzStJDm7Ff0NwOlK9Q0BwZays1BLYOL8Yrpb_v2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);